version: '3'
services:
  web:
    build: ./
    restart: always
    ports:
      - '7001:7001'
    depends_on:
      - db
    container_name: xidao_server_run
  db:
    build: ./
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xiaodao
    volumes:
      - /opt/mysql/:/var/lib/mysql
    container_name: mysql_run
